# Ansible makefile for doing stuff with things.

SHELL=/bin/bash
ANSBIN=/usr/bin/ansible-playbook
# Which roles and collections should be installed? Use dots for roles, slashes for collections
ROLES=gantsign.golang geerlingguy.php-versions jhu-sheridan-libraries.postfix-smarthost geerlingguy.nodejs
COLLECTIONS=vyos/vyos community/general ansible/posix community/docker community/mysql

BINS=$(ANSBIN) /usr/bin/vim /usr/bin/ping /usr/bin/netstat /usr/bin/wget /usr/bin/unzip
PKGS=ansible vim iputils-ping net-tools wget unzip

ANSIBLE_HOST_KEY_CHECKING=False
export ANSIBLE_HOST_KEY_CHECKING

GITCONFIG=$(HOME)/.gitconfig

.PHONY: setup
setup: $(BINS) $(GITCONFIG) group_vars/all/cloudflare.yaml ansible-packages /etc/rc.local fixvim

include $(wildcard includes/Makefile.*)

$(BINS):
	apt-get -y install $(PKGS)

.PHONY: me
me: setup /etc/ansible.hostname
	@MYIPS=$$(ip -o addr | egrep -v '(\ lo|\ docker)' | awk '/inet / { print $$4 }' | cut -d/ -f1 | paste -sd ','); \
		echo ansible-playbook main.yml -l $$MYIPS; \
		ansible-playbook main.yml -l $$MYIPS

.PHONY: base
base /etc/hosts: /etc/ansible.hostname | setup
	$(ANSBIN) basesystem.yml -e hostname=$(shell cat /etc/ansible.hostname)

.PHONY: fhostname
fhostname /etc/ansible.hostname:
	@C=$(shell hostname); echo "Current hostname '$$C'"; read -e -p "Set hostname (blank to not change): " h; \
		if [ "$$h" ]; then \
			echo $$h > /etc/ansible.hostname; \
		else \
			if [ ! -s /etc/ansible.hostname ]; then \
				hostname > /etc/ansible.hostname; \
			fi; \
		fi


GRN=$(HOME)/.gitrealname
GEM=$(HOME)/.gitemail

.PHONY: git regit
git: $(GRN) $(GEM) $(GITCONFIG).user $(GITCONFIG)
	@cat $(GITCONFIG)

regit: force-grn force-gem $(GITCONFIG).user $(GITCONFIG)
	@cat $(GITCONFIG)

.PHONY: force-grn
force-grn $(GRN):
	@D="Rob Thomas"; read -e -p "What is your real name (for $(GITCONFIG)) [$$D]: " h; \
		if [ "$$h" ]; then \
			echo "$$h" > $(GRN); \
		else \
			echo "$$D" > $(GRN); \
		fi

force-gem $(GEM):
	@D="xrobau@gmail.com"; read -e -p "What is your email address (for $(GITCONFIG)) [$$D]: " h; \
		if [ "$$h" ]; then \
			echo "$$h" > $(GEM); \
		else \
			echo "$$D" > $(GEM); \
		fi

# Yeah I'm harcoding 'user' to be xrobau, because then it won't leak the system username
# (eg, root, or debbuild, or whatever) as part of the git commit.
$(GITCONFIG).user: $(GRN) $(GEM)
	@echo -e "# Generated by Makefile\n[user]\n\tuser='xrobau'\n\tname='$$(cat $(GRN))'\n\temail='$$(cat $(GEM))'\n# End generated\n" > $@

$(GITCONFIG): defaults/gitconfig $(GITCONFIG).user
	@cat $(GITCONFIG).user defaults/gitconfig > $@

.PHONY: dev
dev:
	ansible-playbook -i localhost, development.yml -e devmachine=true

cloudflare: group_vars/all/cloudflare.yaml

group_vars/all/cloudflare.yaml: config/cloudflare-ipv4 config/cloudflare-ipv6
	(echo -e "---\ncloudflareips:"; for f in $^; do for ip in $$(cat $$f); do echo "  - \"$$ip\" "; done; done) > $@

config/cloudflare-ipv%:
	wget -O $@ 'https://www.cloudflare.com/ips-v$*/'

# This checks that the machine has hostkeys and a machine-id. Mainly
# used when a VM is broken or has been sysprep'ed
/etc/rc.local: scripts/rc.local
	cp $< $@ && chmod 755 $<

